### Simple Chat: Send message
POST http://localhost:8080/api/chat
Content-Type: application/json

{
    "message": "O que é Spring AI?"
}

### Memory Chat: Create New Chat
POST http://localhost:8080/api/chat-memory/start
Content-Type: application/json

{
    "message": "Tell me a joke about programming"
}

### Variable: Chat ID
@chatId = 9db8a57a-4467-4551-82e3-79175d369ec8

### Memory Chat: Send message to chat
POST http://localhost:8080/api/chat-memory/{{chatId}}
Content-Type: application/json

{
    "message": "Tell me a another joke about programming"
}

### Memory Chat: List chats
GET http://localhost:8080/api/chat-memory
